// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c95mFDtsQD22zpZcHK8Lci
// Component: oa15Iddil2
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navigation from "../../Navigation"; // plasmic-import: suFVYL5EUe/component
import Logo from "../../Logo"; // plasmic-import: ynIdAZgZJy/component
import TitleSubtitle from "../../TitleSubtitle"; // plasmic-import: BzXRBzu1sd/component
import Form from "../../Form"; // plasmic-import: pXYVMs4P-l/component
import Botao from "../../Botao"; // plasmic-import: 2B39Djfxdt/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _eAYH824Sv/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: c95mFDtsQD22zpZcHK8Lci/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: oa15Iddil2/css

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  children?: React.ReactNode;
  farFarAwayBehindTheWordMountainsFarFromTheCountriesVokaliaAndConsonantiaThereLiveTheBlindTexts?: React.ReactNode;
  slot3?: React.ReactNode;
  children2?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>(
  "children",
  "farFarAwayBehindTheWordMountainsFarFromTheCountriesVokaliaAndConsonantiaThereLiveTheBlindTexts",
  "slot3",
  "children2"
);

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  banner?: p.Flex<"div">;
  bg?: p.Flex<"div">;
  logo?: p.Flex<typeof Logo>;
  titleSubtitle?: p.Flex<typeof TitleSubtitle>;
  form?: p.Flex<typeof Form>;
  botao?: p.Flex<typeof Botao>;
  frame8?: p.Flex<"div">;
  rectangle8?: p.Flex<"div">;
  frame?: p.Flex<"div">;
  rectangle?: p.Flex<"div">;
  frame5?: p.Flex<"div">;
  rectangle5?: p.Flex<"div">;
  frame6?: p.Flex<"div">;
  rectangle6?: p.Flex<"div">;
  frame4?: p.Flex<"div">;
  rectangle4?: p.Flex<"div">;
  frame2?: p.Flex<"div">;
  rectangle2?: p.Flex<"div">;
  frame12?: p.Flex<"div">;
  rectangle12?: p.Flex<"div">;
  frame3?: p.Flex<"div">;
  rectangle3?: p.Flex<"div">;
  frame14?: p.Flex<"div">;
  rectangle14?: p.Flex<"div">;
  frame13?: p.Flex<"div">;
  rectangle13?: p.Flex<"div">;
  frame10?: p.Flex<"div">;
  rectangle10?: p.Flex<"div">;
  frame7?: p.Flex<"div">;
  rectangle7?: p.Flex<"div">;
  frame11?: p.Flex<"div">;
  rectangle11?: p.Flex<"div">;
  frame9?: p.Flex<"div">;
  rectangle9?: p.Flex<"div">;
  frame15?: p.Flex<"div">;
  rectangle15?: p.Flex<"div">;
  figmaPaste?: p.Flex<"div">;
  rectangle17?: p.Flex<"div">;
  rectangle18?: p.Flex<"div">;
  rectangle19?: p.Flex<"div">;
  rectangle20?: p.Flex<"div">;
  rectangle21?: p.Flex<"div">;
  rectangle22?: p.Flex<"div">;
  rectangle23?: p.Flex<"div">;
  rectangle24?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
  rectangle27?: p.Flex<"div">;
  rectangle28?: p.Flex<"div">;
  rectangle29?: p.Flex<"div">;
  rectangle30?: p.Flex<"div">;
  rectangle31?: p.Flex<"div">;
  rectangle32?: p.Flex<"div">;
  rectangle33?: p.Flex<"div">;
  rectangle34?: p.Flex<"div">;
  rectangle35?: p.Flex<"div">;
  rectangle36?: p.Flex<"div">;
  rectangle37?: p.Flex<"div">;
  rectangle38?: p.Flex<"div">;
  rectangle39?: p.Flex<"div">;
  rectangle40?: p.Flex<"div">;
  rectangle41?: p.Flex<"div">;
  rectangle42?: p.Flex<"div">;
  rectangle43?: p.Flex<"div">;
  rectangle44?: p.Flex<"div">;
  rectangle45?: p.Flex<"div">;
  rectangle46?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  dataFetches: PlasmicHomepage__Fetches;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <Navigation
              className={classNames("__wab_instance", sty.navigation__nJdmI)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <p.PlasmicLink
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.link__e4P1H
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/" as const}
                    platform={"nextjs"}
                  >
                    {"Politica de Privacidade"}
                  </p.PlasmicLink>
                ),

                value: args.children2
              })}
            </Navigation>
          ) : null}

          <div
            data-plasmic-name={"banner"}
            data-plasmic-override={overrides.banner}
            className={classNames(defaultcss.all, sty.banner)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"bg"}
              data-plasmic-override={overrides.bg}
              hasGap={true}
              className={classNames(defaultcss.all, sty.bg)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox___3RtFf)}>
                <Logo
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames("__wab_instance", sty.logo)}
                />

                <Navigation
                  className={classNames(
                    "__wab_instance",
                    sty.navigation__raeq6
                  )}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: null,
                    value: args.children
                  })}
                </Navigation>
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.columns__zQzMh)}
              >
                <div className={classNames(defaultcss.all, sty.column__xxgqt)}>
                  <TitleSubtitle
                    data-plasmic-name={"titleSubtitle"}
                    data-plasmic-override={overrides.titleSubtitle}
                    className={classNames("__wab_instance", sty.titleSubtitle)}
                    farFarAwayBehindTheWordMountainsFarFromTheCountriesVokaliaAndConsonantiaThereLiveTheBlindTexts={p.renderPlasmicSlot(
                      {
                        defaultContents:
                          "Um projeto completo pra você morar bem, com 12 opções de plantas, torre única e em uma excelente localização. Oben, muito acima do comum.",
                        value:
                          args.farFarAwayBehindTheWordMountainsFarFromTheCountriesVokaliaAndConsonantiaThereLiveTheBlindTexts
                      }
                    )}
                    slot3={p.renderPlasmicSlot({
                      defaultContents: "Conheça o Oben ",
                      value: args.slot3
                    })}
                  />
                </div>

                <div className={classNames(defaultcss.all, sty.column___8Bcnx)}>
                  <Form
                    data-plasmic-name={"form"}
                    data-plasmic-override={overrides.form}
                    className={classNames("__wab_instance", sty.form)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__z6Nuy
                      )}
                    >
                      {"Preencha o Formulário"}
                    </div>
                  </Form>
                </div>
              </p.Stack>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Botao
                  data-plasmic-name={"botao"}
                  data-plasmic-override={overrides.botao}
                  className={classNames("__wab_instance", sty.botao)}
                  ourShowcase={"CONVERSE COM UM CORRETOR"}
                />
              ) : null}
            </p.Stack>
          </div>

          <div className={classNames(defaultcss.all, sty.freeBox__pKhgU)}>
            <div className={classNames(defaultcss.all, sty.freeBox__yCg5A)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__npKQc
                )}
              >
                {"DIFERENCIAIS"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__sXeOz)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.columns__ko6O0)}
              >
                <div className={classNames(defaultcss.all, sty.column__gqib0)}>
                  <div
                    data-plasmic-name={"frame8"}
                    data-plasmic-override={overrides.frame8}
                    className={classNames(defaultcss.all, sty.frame8)}
                  >
                    <div
                      data-plasmic-name={"rectangle8"}
                      data-plasmic-override={overrides.rectangle8}
                      className={classNames(defaultcss.all, sty.rectangle8)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__lATer
                      )}
                    >
                      {"Medidores individuais para energia, água e gás"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    className={classNames(defaultcss.all, sty.frame)}
                  >
                    <div
                      data-plasmic-name={"rectangle"}
                      data-plasmic-override={overrides.rectangle}
                      className={classNames(defaultcss.all, sty.rectangle)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__yQzk7
                      )}
                    >
                      {"Antissucção piscina"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    className={classNames(defaultcss.all, sty.frame5)}
                  >
                    <div
                      data-plasmic-name={"rectangle5"}
                      data-plasmic-override={overrides.rectangle5}
                      className={classNames(defaultcss.all, sty.rectangle5)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__wlXjy
                      )}
                    >
                      {"Descarte seletivo"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(defaultcss.all, sty.frame6)}
                  >
                    <div
                      data-plasmic-name={"rectangle6"}
                      data-plasmic-override={overrides.rectangle6}
                      className={classNames(defaultcss.all, sty.rectangle6)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___84Br
                      )}
                    >
                      {"Sistema dual flush"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    className={classNames(defaultcss.all, sty.frame4)}
                  >
                    <div
                      data-plasmic-name={"rectangle4"}
                      data-plasmic-override={overrides.rectangle4}
                      className={classNames(defaultcss.all, sty.rectangle4)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__bfKx0
                      )}
                    >
                      {"Áreas de lazer entregues equipadas e decoradas"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    className={classNames(defaultcss.all, sty.frame2)}
                  >
                    <div
                      data-plasmic-name={"rectangle2"}
                      data-plasmic-override={overrides.rectangle2}
                      className={classNames(defaultcss.all, sty.rectangle2)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__azPc4
                      )}
                    >
                      {"Automação das áreas comuns"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame12"}
                    data-plasmic-override={overrides.frame12}
                    className={classNames(defaultcss.all, sty.frame12)}
                  >
                    <div
                      data-plasmic-name={"rectangle12"}
                      data-plasmic-override={overrides.rectangle12}
                      className={classNames(defaultcss.all, sty.rectangle12)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__tEzo8
                      )}
                    >
                      {"Wifi nas áreas de lazer"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    className={classNames(defaultcss.all, sty.frame3)}
                  >
                    <div
                      data-plasmic-name={"rectangle3"}
                      data-plasmic-override={overrides.rectangle3}
                      className={classNames(defaultcss.all, sty.rectangle3)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___77Ymy
                      )}
                    >
                      {"Ambientes internos de lazer climatizados"}
                    </div>
                  </div>
                </div>

                <div className={classNames(defaultcss.all, sty.column__lN1Gc)}>
                  <div
                    data-plasmic-name={"frame14"}
                    data-plasmic-override={overrides.frame14}
                    className={classNames(defaultcss.all, sty.frame14)}
                  >
                    <div
                      data-plasmic-name={"rectangle14"}
                      data-plasmic-override={overrides.rectangle14}
                      className={classNames(defaultcss.all, sty.rectangle14)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__jAtgL
                      )}
                    >
                      {"Ponto para carga de carro elétrico."}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame13"}
                    data-plasmic-override={overrides.frame13}
                    className={classNames(defaultcss.all, sty.frame13)}
                  >
                    <div
                      data-plasmic-name={"rectangle13"}
                      data-plasmic-override={overrides.rectangle13}
                      className={classNames(defaultcss.all, sty.rectangle13)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___6Cgif
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Torneiras com temporizador nos sanitários das áreas de lazer"
                        : "Torneiras com temporizador nos sanitários das áreas de lazer"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame10"}
                    data-plasmic-override={overrides.frame10}
                    className={classNames(defaultcss.all, sty.frame10)}
                  >
                    <div
                      data-plasmic-name={"rectangle10"}
                      data-plasmic-override={overrides.rectangle10}
                      className={classNames(defaultcss.all, sty.rectangle10)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__tp3C
                      )}
                    >
                      {"Estacionamento coberto"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame7"}
                    data-plasmic-override={overrides.frame7}
                    className={classNames(defaultcss.all, sty.frame7)}
                  >
                    <div
                      data-plasmic-name={"rectangle7"}
                      data-plasmic-override={overrides.rectangle7}
                      className={classNames(defaultcss.all, sty.rectangle7)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__krJnr
                      )}
                    >
                      {"Portas e guarnições com madeira certificada"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame11"}
                    data-plasmic-override={overrides.frame11}
                    className={classNames(defaultcss.all, sty.frame11)}
                  >
                    <div
                      data-plasmic-name={"rectangle11"}
                      data-plasmic-override={overrides.rectangle11}
                      className={classNames(defaultcss.all, sty.rectangle11)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__mArBc
                      )}
                    >
                      {
                        "Esquadrias integradas com venezianas deslizantes nos dormitórios"
                      }
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame9"}
                    data-plasmic-override={overrides.frame9}
                    className={classNames(defaultcss.all, sty.frame9)}
                  >
                    <div
                      data-plasmic-name={"rectangle9"}
                      data-plasmic-override={overrides.rectangle9}
                      className={classNames(defaultcss.all, sty.rectangle9)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__cZbtk
                      )}
                    >
                      {"Sensores de presença nas áreas comuns"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame15"}
                    data-plasmic-override={overrides.frame15}
                    className={classNames(defaultcss.all, sty.frame15)}
                  >
                    <div
                      data-plasmic-name={"rectangle15"}
                      data-plasmic-override={overrides.rectangle15}
                      className={classNames(defaultcss.all, sty.rectangle15)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___12J8L
                      )}
                    >
                      {
                        "Entradas independentes para moradores, visitantes e serviços com espera"
                      }
                    </div>
                  </div>
                </div>
              </p.Stack>
            </p.Stack>
          </div>

          <div className={classNames(defaultcss.all, sty.freeBox__foTho)}>
            <div
              data-plasmic-name={"figmaPaste"}
              data-plasmic-override={overrides.figmaPaste}
              className={classNames(defaultcss.all, sty.figmaPaste)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__gsDYd)} />

              <div className={classNames(defaultcss.all, sty.freeBox__ltGec)} />

              <div className={classNames(defaultcss.all, sty.freeBox__uzMyx)} />

              <div
                className={classNames(defaultcss.all, sty.freeBox___3Z5Pn)}
              />

              <div className={classNames(defaultcss.all, sty.freeBox__vrJ5U)} />

              <div className={classNames(defaultcss.all, sty.freeBox__g0Mld)} />

              <div className={classNames(defaultcss.all, sty.freeBox__dHhHh)} />

              <div className={classNames(defaultcss.all, sty.freeBox__zrb4V)} />

              <div className={classNames(defaultcss.all, sty.freeBox__biHTx)} />

              <div className={classNames(defaultcss.all, sty.freeBox__oKmLi)} />

              <div className={classNames(defaultcss.all, sty.freeBox__rLKn)} />

              <div className={classNames(defaultcss.all, sty.freeBox__ntt8A)} />

              <div className={classNames(defaultcss.all, sty.freeBox__gHbJ)} />

              <div className={classNames(defaultcss.all, sty.freeBox__tku4S)} />

              <div className={classNames(defaultcss.all, sty.freeBox__iyJeh)} />

              <div className={classNames(defaultcss.all, sty.freeBox__xwtpX)} />

              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(defaultcss.all, sty.rectangle17)}
              />

              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />

              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(defaultcss.all, sty.rectangle19)}
              />

              <div
                data-plasmic-name={"rectangle20"}
                data-plasmic-override={overrides.rectangle20}
                className={classNames(defaultcss.all, sty.rectangle20)}
              />

              <div
                data-plasmic-name={"rectangle21"}
                data-plasmic-override={overrides.rectangle21}
                className={classNames(defaultcss.all, sty.rectangle21)}
              />

              <div
                data-plasmic-name={"rectangle22"}
                data-plasmic-override={overrides.rectangle22}
                className={classNames(defaultcss.all, sty.rectangle22)}
              />

              <div
                data-plasmic-name={"rectangle23"}
                data-plasmic-override={overrides.rectangle23}
                className={classNames(defaultcss.all, sty.rectangle23)}
              />

              <div
                data-plasmic-name={"rectangle24"}
                data-plasmic-override={overrides.rectangle24}
                className={classNames(defaultcss.all, sty.rectangle24)}
              />

              <div
                data-plasmic-name={"rectangle25"}
                data-plasmic-override={overrides.rectangle25}
                className={classNames(defaultcss.all, sty.rectangle25)}
              />

              <div
                data-plasmic-name={"rectangle26"}
                data-plasmic-override={overrides.rectangle26}
                className={classNames(defaultcss.all, sty.rectangle26)}
              />

              <div
                data-plasmic-name={"rectangle27"}
                data-plasmic-override={overrides.rectangle27}
                className={classNames(defaultcss.all, sty.rectangle27)}
              />

              <div
                data-plasmic-name={"rectangle28"}
                data-plasmic-override={overrides.rectangle28}
                className={classNames(defaultcss.all, sty.rectangle28)}
              />

              <div
                data-plasmic-name={"rectangle29"}
                data-plasmic-override={overrides.rectangle29}
                className={classNames(defaultcss.all, sty.rectangle29)}
              />

              <div
                data-plasmic-name={"rectangle30"}
                data-plasmic-override={overrides.rectangle30}
                className={classNames(defaultcss.all, sty.rectangle30)}
              />

              <div
                data-plasmic-name={"rectangle31"}
                data-plasmic-override={overrides.rectangle31}
                className={classNames(defaultcss.all, sty.rectangle31)}
              />

              <div
                data-plasmic-name={"rectangle32"}
                data-plasmic-override={overrides.rectangle32}
                className={classNames(defaultcss.all, sty.rectangle32)}
              />

              <div
                data-plasmic-name={"rectangle33"}
                data-plasmic-override={overrides.rectangle33}
                className={classNames(defaultcss.all, sty.rectangle33)}
              />

              <div
                data-plasmic-name={"rectangle34"}
                data-plasmic-override={overrides.rectangle34}
                className={classNames(defaultcss.all, sty.rectangle34)}
              />

              <div
                data-plasmic-name={"rectangle35"}
                data-plasmic-override={overrides.rectangle35}
                className={classNames(defaultcss.all, sty.rectangle35)}
              />

              <div
                data-plasmic-name={"rectangle36"}
                data-plasmic-override={overrides.rectangle36}
                className={classNames(defaultcss.all, sty.rectangle36)}
              />

              <div
                data-plasmic-name={"rectangle37"}
                data-plasmic-override={overrides.rectangle37}
                className={classNames(defaultcss.all, sty.rectangle37)}
              />

              <div
                data-plasmic-name={"rectangle38"}
                data-plasmic-override={overrides.rectangle38}
                className={classNames(defaultcss.all, sty.rectangle38)}
              />

              <div
                data-plasmic-name={"rectangle39"}
                data-plasmic-override={overrides.rectangle39}
                className={classNames(defaultcss.all, sty.rectangle39)}
              />

              <div
                data-plasmic-name={"rectangle40"}
                data-plasmic-override={overrides.rectangle40}
                className={classNames(defaultcss.all, sty.rectangle40)}
              />

              <div
                data-plasmic-name={"rectangle41"}
                data-plasmic-override={overrides.rectangle41}
                className={classNames(defaultcss.all, sty.rectangle41)}
              />

              <div
                data-plasmic-name={"rectangle42"}
                data-plasmic-override={overrides.rectangle42}
                className={classNames(defaultcss.all, sty.rectangle42)}
              />

              <div
                data-plasmic-name={"rectangle43"}
                data-plasmic-override={overrides.rectangle43}
                className={classNames(defaultcss.all, sty.rectangle43)}
              />

              <div
                data-plasmic-name={"rectangle44"}
                data-plasmic-override={overrides.rectangle44}
                className={classNames(defaultcss.all, sty.rectangle44)}
              />

              <div
                data-plasmic-name={"rectangle45"}
                data-plasmic-override={overrides.rectangle45}
                className={classNames(defaultcss.all, sty.rectangle45)}
              />

              <div
                data-plasmic-name={"rectangle46"}
                data-plasmic-override={overrides.rectangle46}
                className={classNames(defaultcss.all, sty.rectangle46)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__wImJz
                )}
              >
                {"The Beauty of Contrast"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__gUA4
                )}
              >
                {"We turn you on to pro lighting strategies to highlight"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___15Wy
                )}
              >
                {"the most of indoor and outdoor rooms"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__tmsnn
                )}
              >
                {"Beautiful New Kitchen"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__xhYyv
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__aoBaW
                )}
              >
                {"Total Price: $15,000"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__pfOmU
                )}
              >
                {"40 m²"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__zbIkZ
                )}
              >
                {"Green Garden"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__dOtFw
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___0Lqmy
                )}
              >
                {"Total Price: $3,000"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__cwp4Z
                )}
              >
                {"35 m²"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___5Kf9T
                )}
              >
                {"The New House"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__xOL1
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__l3Ekd
                )}
              >
                {"Total Price: $23,500"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__nwYEk
                )}
              >
                {"120 m²"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__a5LIh
                )}
              >
                {"Great Town Flat"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__owgdU
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__zZprx
                )}
              >
                {"Total Price: $35,000"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__wy4Sm
                )}
              >
                {"180 m²"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__nOsVn
                )}
              >
                {"Salon with Space"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__fQhc3
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__gIcO3
                )}
              >
                {"Total Price: $8,000"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__cmbXm
                )}
              >
                {"80 m²"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__mfKt
                )}
              >
                {"Village Villa"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__iIkuy
                )}
              >
                {
                  "great deal with awesome new features it is realy incredible design and price."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__suhQo
                )}
              >
                {"Total Price: $42,500"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__bKuw
                )}
              >
                {"320 m²"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "banner",
    "bg",
    "logo",
    "titleSubtitle",
    "form",
    "botao",
    "frame8",
    "rectangle8",
    "frame",
    "rectangle",
    "frame5",
    "rectangle5",
    "frame6",
    "rectangle6",
    "frame4",
    "rectangle4",
    "frame2",
    "rectangle2",
    "frame12",
    "rectangle12",
    "frame3",
    "rectangle3",
    "frame14",
    "rectangle14",
    "frame13",
    "rectangle13",
    "frame10",
    "rectangle10",
    "frame7",
    "rectangle7",
    "frame11",
    "rectangle11",
    "frame9",
    "rectangle9",
    "frame15",
    "rectangle15",
    "figmaPaste",
    "rectangle17",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "rectangle29",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "rectangle33",
    "rectangle34",
    "rectangle35",
    "rectangle36",
    "rectangle37",
    "rectangle38",
    "rectangle39",
    "rectangle40",
    "rectangle41",
    "rectangle42",
    "rectangle43",
    "rectangle44",
    "rectangle45",
    "rectangle46"
  ],
  banner: ["banner", "bg", "logo", "titleSubtitle", "form", "botao"],
  bg: ["bg", "logo", "titleSubtitle", "form", "botao"],
  logo: ["logo"],
  titleSubtitle: ["titleSubtitle"],
  form: ["form"],
  botao: ["botao"],
  frame8: ["frame8", "rectangle8"],
  rectangle8: ["rectangle8"],
  frame: ["frame", "rectangle"],
  rectangle: ["rectangle"],
  frame5: ["frame5", "rectangle5"],
  rectangle5: ["rectangle5"],
  frame6: ["frame6", "rectangle6"],
  rectangle6: ["rectangle6"],
  frame4: ["frame4", "rectangle4"],
  rectangle4: ["rectangle4"],
  frame2: ["frame2", "rectangle2"],
  rectangle2: ["rectangle2"],
  frame12: ["frame12", "rectangle12"],
  rectangle12: ["rectangle12"],
  frame3: ["frame3", "rectangle3"],
  rectangle3: ["rectangle3"],
  frame14: ["frame14", "rectangle14"],
  rectangle14: ["rectangle14"],
  frame13: ["frame13", "rectangle13"],
  rectangle13: ["rectangle13"],
  frame10: ["frame10", "rectangle10"],
  rectangle10: ["rectangle10"],
  frame7: ["frame7", "rectangle7"],
  rectangle7: ["rectangle7"],
  frame11: ["frame11", "rectangle11"],
  rectangle11: ["rectangle11"],
  frame9: ["frame9", "rectangle9"],
  rectangle9: ["rectangle9"],
  frame15: ["frame15", "rectangle15"],
  rectangle15: ["rectangle15"],
  figmaPaste: [
    "figmaPaste",
    "rectangle17",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "rectangle29",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "rectangle33",
    "rectangle34",
    "rectangle35",
    "rectangle36",
    "rectangle37",
    "rectangle38",
    "rectangle39",
    "rectangle40",
    "rectangle41",
    "rectangle42",
    "rectangle43",
    "rectangle44",
    "rectangle45",
    "rectangle46"
  ],
  rectangle17: ["rectangle17"],
  rectangle18: ["rectangle18"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  rectangle22: ["rectangle22"],
  rectangle23: ["rectangle23"],
  rectangle24: ["rectangle24"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  rectangle29: ["rectangle29"],
  rectangle30: ["rectangle30"],
  rectangle31: ["rectangle31"],
  rectangle32: ["rectangle32"],
  rectangle33: ["rectangle33"],
  rectangle34: ["rectangle34"],
  rectangle35: ["rectangle35"],
  rectangle36: ["rectangle36"],
  rectangle37: ["rectangle37"],
  rectangle38: ["rectangle38"],
  rectangle39: ["rectangle39"],
  rectangle40: ["rectangle40"],
  rectangle41: ["rectangle41"],
  rectangle42: ["rectangle42"],
  rectangle43: ["rectangle43"],
  rectangle44: ["rectangle44"],
  rectangle45: ["rectangle45"],
  rectangle46: ["rectangle46"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  banner: "div";
  bg: "div";
  logo: typeof Logo;
  titleSubtitle: typeof TitleSubtitle;
  form: typeof Form;
  botao: typeof Botao;
  frame8: "div";
  rectangle8: "div";
  frame: "div";
  rectangle: "div";
  frame5: "div";
  rectangle5: "div";
  frame6: "div";
  rectangle6: "div";
  frame4: "div";
  rectangle4: "div";
  frame2: "div";
  rectangle2: "div";
  frame12: "div";
  rectangle12: "div";
  frame3: "div";
  rectangle3: "div";
  frame14: "div";
  rectangle14: "div";
  frame13: "div";
  rectangle13: "div";
  frame10: "div";
  rectangle10: "div";
  frame7: "div";
  rectangle7: "div";
  frame11: "div";
  rectangle11: "div";
  frame9: "div";
  rectangle9: "div";
  frame15: "div";
  rectangle15: "div";
  figmaPaste: "div";
  rectangle17: "div";
  rectangle18: "div";
  rectangle19: "div";
  rectangle20: "div";
  rectangle21: "div";
  rectangle22: "div";
  rectangle23: "div";
  rectangle24: "div";
  rectangle25: "div";
  rectangle26: "div";
  rectangle27: "div";
  rectangle28: "div";
  rectangle29: "div";
  rectangle30: "div";
  rectangle31: "div";
  rectangle32: "div";
  rectangle33: "div";
  rectangle34: "div";
  rectangle35: "div";
  rectangle36: "div";
  rectangle37: "div";
  rectangle38: "div";
  rectangle39: "div";
  rectangle40: "div";
  rectangle41: "div";
  rectangle42: "div";
  rectangle43: "div";
  rectangle44: "div";
  rectangle45: "div";
  rectangle46: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    banner: makeNodeComponent("banner"),
    bg: makeNodeComponent("bg"),
    logo: makeNodeComponent("logo"),
    titleSubtitle: makeNodeComponent("titleSubtitle"),
    form: makeNodeComponent("form"),
    botao: makeNodeComponent("botao"),
    frame8: makeNodeComponent("frame8"),
    rectangle8: makeNodeComponent("rectangle8"),
    frame: makeNodeComponent("frame"),
    rectangle: makeNodeComponent("rectangle"),
    frame5: makeNodeComponent("frame5"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame6: makeNodeComponent("frame6"),
    rectangle6: makeNodeComponent("rectangle6"),
    frame4: makeNodeComponent("frame4"),
    rectangle4: makeNodeComponent("rectangle4"),
    frame2: makeNodeComponent("frame2"),
    rectangle2: makeNodeComponent("rectangle2"),
    frame12: makeNodeComponent("frame12"),
    rectangle12: makeNodeComponent("rectangle12"),
    frame3: makeNodeComponent("frame3"),
    rectangle3: makeNodeComponent("rectangle3"),
    frame14: makeNodeComponent("frame14"),
    rectangle14: makeNodeComponent("rectangle14"),
    frame13: makeNodeComponent("frame13"),
    rectangle13: makeNodeComponent("rectangle13"),
    frame10: makeNodeComponent("frame10"),
    rectangle10: makeNodeComponent("rectangle10"),
    frame7: makeNodeComponent("frame7"),
    rectangle7: makeNodeComponent("rectangle7"),
    frame11: makeNodeComponent("frame11"),
    rectangle11: makeNodeComponent("rectangle11"),
    frame9: makeNodeComponent("frame9"),
    rectangle9: makeNodeComponent("rectangle9"),
    frame15: makeNodeComponent("frame15"),
    rectangle15: makeNodeComponent("rectangle15"),
    figmaPaste: makeNodeComponent("figmaPaste"),
    rectangle17: makeNodeComponent("rectangle17"),
    rectangle18: makeNodeComponent("rectangle18"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    rectangle22: makeNodeComponent("rectangle22"),
    rectangle23: makeNodeComponent("rectangle23"),
    rectangle24: makeNodeComponent("rectangle24"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle29: makeNodeComponent("rectangle29"),
    rectangle30: makeNodeComponent("rectangle30"),
    rectangle31: makeNodeComponent("rectangle31"),
    rectangle32: makeNodeComponent("rectangle32"),
    rectangle33: makeNodeComponent("rectangle33"),
    rectangle34: makeNodeComponent("rectangle34"),
    rectangle35: makeNodeComponent("rectangle35"),
    rectangle36: makeNodeComponent("rectangle36"),
    rectangle37: makeNodeComponent("rectangle37"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle39: makeNodeComponent("rectangle39"),
    rectangle40: makeNodeComponent("rectangle40"),
    rectangle41: makeNodeComponent("rectangle41"),
    rectangle42: makeNodeComponent("rectangle42"),
    rectangle43: makeNodeComponent("rectangle43"),
    rectangle44: makeNodeComponent("rectangle44"),
    rectangle45: makeNodeComponent("rectangle45"),
    rectangle46: makeNodeComponent("rectangle46"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
