// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c95mFDtsQD22zpZcHK8Lci
// Component: 2B39Djfxdt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: c95mFDtsQD22zpZcHK8Lci/projectcss
import * as sty from "./PlasmicBotao.module.css"; // plasmic-import: 2B39Djfxdt/css

import IconArrowIcon from "./icons/PlasmicIcon__IconArrow"; // plasmic-import: xjviC_Dak_/icon

export type PlasmicBotao__VariantMembers = {};

export type PlasmicBotao__VariantsArgs = {};
type VariantPropType = keyof PlasmicBotao__VariantsArgs;
export const PlasmicBotao__VariantProps = new Array<VariantPropType>();

export type PlasmicBotao__ArgsType = {
  ourShowcase?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBotao__ArgsType;
export const PlasmicBotao__ArgProps = new Array<ArgPropType>("ourShowcase");

export type PlasmicBotao__OverridesType = {
  root?: p.Flex<"div">;
  bg2?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultBotaoProps {
  ourShowcase?: React.ReactNode;
  className?: string;
}

function PlasmicBotao__RenderFunc(props: {
  variants: PlasmicBotao__VariantsArgs;
  args: PlasmicBotao__ArgsType;
  overrides: PlasmicBotao__OverridesType;
  dataFetches?: PlasmicBotao__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox__iiLcS)}>
        <div
          data-plasmic-name={"bg2"}
          data-plasmic-override={overrides.bg2}
          className={classNames(defaultcss.all, sty.bg2)}
        >
          <IconArrowIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(defaultcss.all, sty.svg)}
            role={"img"}
          />

          <div className={classNames(defaultcss.all, sty.freeBox__lJYsk)}>
            {p.renderPlasmicSlot({
              defaultContents: "CONVERSE COM UM CORRETOR",
              value: args.ourShowcase,
              className: classNames(sty.slotTargetOurShowcase)
            })}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "bg2", "svg"],
  bg2: ["bg2", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  bg2: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBotao__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBotao__VariantsArgs;
    args?: PlasmicBotao__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBotao__Fetches;
  } & Omit<PlasmicBotao__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBotao__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBotao__ArgProps,
      internalVariantPropNames: PlasmicBotao__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBotao__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBotao";
  } else {
    func.displayName = `PlasmicBotao.${nodeName}`;
  }
  return func;
}

export const PlasmicBotao = Object.assign(
  // Top-level PlasmicBotao renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bg2: makeNodeComponent("bg2"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicBotao
    internalVariantProps: PlasmicBotao__VariantProps,
    internalArgProps: PlasmicBotao__ArgProps
  }
);

export default PlasmicBotao;
/* prettier-ignore-end */
